### PR TITLE
Speed improvements

### PR DESCRIPTION
**Pull request by fegies**
This Pull requests aims to improve the processing speed by avoiding the construction of serde-value objects (they are implemented as B-Trees), leading to many allocations for every proto message.

For my test case (converting 200k fairly heavy protobuf messages) I was able to observe the following speed improvements:

Before:
$ time ./pq --msgtype simmo.TranshipmentCandidate --fdsetdir ./fdset --stream i32be < candidates.proto.ld > /dev/null
real    2m20.320s
user    3m7.052s
sys     0m20.936s

After:

$ time ./pq --msgtype simmo.TranshipmentCandidate --fdsetdir ./fdset --stream i32be < candidates.proto.ld > /dev/null
real    1m19.370s
user    1m14.457s
sys     0m4.568s

Here you can see flamegraphs clearly showing the allocations taking a lot of cpu time:
flame_before
And after:
flame_after

### CODE REVIEW

**Comment by fegies** [comment]
Coincidentally, this also fixes #95 since the unbounded queue has been removed.

**Comment by sevagh** [comment]
This is excellent. I'll need some time to refamiliarize myself with this code, fetch your branch, compile it, run the tests, etc. But - thanks in advance for the contribution.

**Comment by fegies** [comment]
It might also be possible to save on the allocation per message by avoiding the Iterator interface and instead providing a function like 
next_preallocated<'a>(&muf self, buf: &'a mut Vec<u8>) -> Option<&'a [u8]>,
on the ByteConsumer Trait.
and then changing the main loop from for... to while let ...


I am not sure about the performance improvements there though

**Comment by sevagh** [comment]
>Since this would requires some changes in the interface to the stream-delimit subcrate, I'd open a new pullrequest for discussion if you are open to the idea.

I'm open.

**Comment by sevagh** [comment]
I have time to clone and test this today.

**Comment by sevagh** [comment]
Can you compare your code against this previous (merged) PR: https://github.com/sevagh/pq/pull/81

That PR added the call to "spawn" in the first place, and now I see you're removing that part.

**Comment by fegies** [comment]
> Can you compare your code against this previous (merged) PR: #81

I am not sure what you mean by compare, as the first measurement (and flamegraph) is already done on master, which includes the threaded code

Regarding the removal of the threads, its still faster because:
The main reason for the speedup in this case is the fact that we can avoid constructing an itermediate value, and so only have to traverse each message once.
This means that we cant run decoding and encoding in separarate threads though.

In theory it might be possible to parallelize on a message level (transcoding multiple messages simultaneously)
I cant think of an easy way to do it without giving up ordering guarantees in the output though.

**Comment by sevagh** [comment]
Just wanted to make sure we're not walking back any desired behavior. Anyway it looks OK on my end, performance improved.

**Comment by sevagh** [comment]
Thanks. I could either cut a release or wait for the next idea you had.

**Pull request merged**
