### PR TITLE
Add i32be stream type

### PR DESCRIPTION
**Pull request by romand**
So we can pipe `kafkacat` output to pq:
```
kafkacat -b 192.168.0.1:9092 -C -u -q -f "%R%s" -t my_topic |\
> pq --msgtype=com.example.dog.Dog --stream i32be
```
`kafkacat -f "%R%s"` outputs messages delimited by payload length
serialized as a binary big endian 32-bit signed integer.

### CODE REVIEW

**Comment by sevagh** [comment]
Thanks - I'll take a look at this ASAP.

**Comment by sevagh** [comment]
Could you add a basic test like:
https://github.com/sevagh/pq/blob/master/stream-delimit/src/varint.rs#L57

And a more complex test like:
https://github.com/sevagh/pq/blob/master/tests/test_pqrs_bin.rs#L26

To add something like `test_dog_decode_stream_i32be` you could capture the output of `kafkacat -b 192.168.0.1:9092 -C -u -q -f "%R%s" -t my_topic` (if you have that set up) and put it in https://github.com/sevagh/pq/tree/master/tests/samples, in a file called `dog_stream_i32be` perhaps?

**Comment by romand** [comment]
Added tests.
Not sure about basic one though: it basically tests `byteorder`…
Btw, `test_pqrs_bin.rs` doesn't pass, seeming because of smth unrelated to this PR.

**Comment by sevagh** [comment]
Yeah, I guess you're right. It's OK though, it's still "proof" that it works? ¯\_(ツ)_/¯

I pulled your fork and the tests look good to me (`make test` runs the tests in a Docker container - maybe `cargo test` doesn't work right?):

```
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running `/volume/target/x86_64-unknown-linux-musl/debug/deps/test_pqrs_bin-ca4e37a624a6bfd0`

running 12 tests
test test_cat_canonical_decode ... ignored
test test_cat_noncanonical_decode ... ok
test test_dog_decode ... ok
test test_bad_input ... ok
test test_dog_decode_i32be_stream ... ok
test test_dog_decode_stream ... ok
test test_no_args ... ok
test test_no_fdset_files ... ok
test test_nonexistent_fdset_dir ... ok
test test_person_decode ... ok
test test_person_decode_with_command_line_fdset_dir ... ok
test test_person_decode_with_command_line_fdset_file ... ok

```

**Comment by sevagh** [comment]
Thanks for the contribution.

**Pull request merged**
